name: Drift Detection

on:  
  workflow_dispatch:
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '0 0 * * *'

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    steps:
    - name: digger drift detection
      uses: diggerhq/digger-ee@vee-drift-as-issues
      with:
        mode: drift-detection
        setup-terragrunt: true
        setup-aws: true
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        digger-token: ${{ secrets.DIGGER_TOKEN }}
        digger-organisation: digger
        digger-hostname: https://cloud.digger.dev/
        drift-detection-slack-notification-url: ${{ secrets.DRIFT_DETECTION_SLACK_NOTIFICATION }}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DIGGER_GITHUB_TOKEN: ${{ secrets.DIGGER_GITHUB_TOKEN }}
        INPUT_DRIFT_GITHUB_ISSUES: 'true'
        DIGGER_MANAGEMENT_REPO: "https://github.com/diggerhq/mgmt-repo-one"
